---
- name: "Workstation"
  hosts: localhost
  connection: local
  roles:
    - workstation
  vars:
    homebrew_taps:
      - warrensbox/tap
      - homebrew/cask-fonts
      - oven-sh/bun
    homebrew_packages:
      - zsh
      - gh
      - terraform-docs
      - ripgrep
      - awscli
      - defaultbrowser
      - ansible
      - neovim
      - git
      - tree
      - kubectl
      - helm
      - tfenv
      - warrensbox/tap/tgswitch
      - golang
      - ruby
      - jq
      - vault
      - thefuck
      - mas
      - tmux
      - ruby-build
      - rbenv
      - bat
      - fd
      - git-delta
      - fzf
      - aws-vault
      - curl
      - semgrep
      - graphviz
      - tgswitch
      - bat-extras
      - pre-commit
      - bun
      - python@3.12
      - pipenv
      - sops
      - kubergrunt
      - flyctl
      - 1password-cli
      - k9s
      - docker
      - gum
    homebrew_casks:
      - font-hack-nerd-font
      - visual-studio-code
      - github
      - iterm2
      - rectangle
      - podman-desktop
      - signal
      - figma
      - notion
      - basecamp
      - loom
