---
- name: "Workstation"
  hosts: localhost
  connection: local
  roles:
    - workstation
  vars:
    homebrew_packages:
      - zsh
      - gh
      - terraform-docs
      - ripgrep
      - awscli
      - defaultbrowser
      - ansible
      - neovim
      - git
      - tree
      - kubectl
      - helm
      - tfenv
      - warrensbox/tap/tgswitch
      - golang
      - ruby
      - jq
      - vault
      - thefuck
      - mas
      - tmux
      - ruby-build
      - rbenv
      - bat
      - fd
      - git-delta
      - fzf
      - aws-vault
      - curl
    homebrew_casks:
      - visual-studio-code
      - github
      - iterm2
      - rectangle
      - podman-desktop
      - signal
      - figma
      - notion
      - basecamp
      - loom
