---
- name: Freeform
  shell: '$HOME/usr/local/bin/dockutil $HOME/Library/Preferences/com.apple.dock.plist --remove {{ item }}'
  loop: '{{ workstation_dockutil_removes }}'
  register: dockutil_output
  changed_when: dockutil_output.rc == 0
  ignore_errors: true
