---
- name: Remove Unwanted Dock Items
  shell: '$HOME/usr/local/bin/dockutil --remove {{ item }} --no-restart'
  loop: '{{ workstation_dockutil_removes }}'
  register: dockutil_output
  changed_when: dockutil_output.rc == 0
  failed_when: dockutil_output.rc > 1
  ignore_errors: true
- name: Restart the Dock
  shell: '/usr/bin/killall Dock'
  when: dockutil_output.changed
