- name: Get github metadata
  uri:
    url: https://api.github.com/meta
  register: githubmeta
- name: Ensure .ssh exists
  file:
    path: ~/.ssh
    state: directory
    mode: '0755'
- name: Ensure known_hosts exists
  copy:
    content: ''
    dest: ~/.ssh/known_hosts
    mode: '0600'
    force: false
- name: Ensure github.com known_host entries are correct
  lineinfile:
    path: ~/.ssh/known_hosts
    regexp: '^github.com\s+{{ item.split(" ")[0] | regex_escape() }}\s+.*$'
    line: 'github.com {{ item }}'
  loop: "{{ githubmeta['json']['ssh_keys'] }}"
  loop_control:
    label: "{{ item.split(' ')[0] }}"
