- name: Enable Rosetta2
  shell:
    cmd: softwareupdate --install-rosetta --agree-to-license
    creates: /usr/libexec/rosetta/oahd
- include_tasks: packages.yml
- include_tasks: dotfiles.yml
- include_tasks: dockutil.yml
- include_tasks: github_known_hosts.yml
- git:
    repo: git@github.com:sorin-ionescu/prezto.git
    dest: ~/.zprezto
    recursive: true
- name: Set Chrome as the default browser
  script: "{{ role_path }}/files/ChromeDefault.scpt"
  args:
    executable: osascript
