- name: Enable Rosetta
  shell:
    cmd: softwareupdate --install-rosetta --agree-to-license
    creates: /usr/libexec/rosetta/oahd
- homebrew:
    update_homebrew: yes
    upgrade_all: yes
    upgrade_options: ignore-pinned
- homebrew:
    name:
      - defaultbrowser
      - ansible
      - neovim
      - git
      - tree
      - kubectl
      - helm
      - terraform
      - golang
      - ruby
      - httpie
      - jq
      - vault
      - fluxcd/tap/flux
      - thefuck
      - pnpm
- homebrew_cask:
    upgrade_all: true
- homebrew_cask:
    name:
      - visual-studio-code
      - google-chrome
      - keybase
      - iterm2
      - warp
      - rectangle
      - podman-desktop
- name: Copy ChromeDefault script
  copy:
    src: ChromeDefault.scpt
    dest: /tmp/ChromeDefault.scpt
- name: Set Chrome as the default browser
  shell:
    cmd: osascript /tmp/ChromeDefault.scpt
