- homebrew:
    update_homebrew: yes
    upgrade_all: yes
    upgrade_options: ignore-pinned
- homebrew:
    name:
      - ansible
      - neovim
      - git
      - tree
      - kubectl
      - helm
      - terraform
      - golang
      - ruby
      - httpie
      - jq
      - vault
      - fluxcd/tap/flux
      - thefuck
- homebrew_cask:
    upgrade_all: true
- homebrew_cask:
    name:
      - visual-studio-code
      - keybase
      - iterm2
      - warp
      - rectangle
      - podman-desktop
