- homebrew:
    name:
      - zsh
      - gh
      - terraform-docs
      - ripgrep
      - awscli
      - defaultbrowser
      - ansible
      - neovim
      - git
      - tree
      - kubectl
      - helm
      - tfenv
      - warrensbox/tap/tgswitch
      - golang
      - ruby
      - jq
      - vault
      - thefuck
      - mas
      - tmux
      - ruby-build
      - rbenv
      - bat
      - fd
      - git-delta
      - fzf
      - aws-vault
- homebrew_cask:
    accept_external_apps: true
    name:
      - visual-studio-code
      - github
      - iterm2
      - rectangle
      - podman-desktop
      - signal
      - figma
      - notion
      - basecamp
      - loom
- name: Install AppStore Apps
  mas:
    state: present
    id:
      - 585829637 # Todoist

# Potentially super slow stuff
- find:
    paths: /tmp
    pattern: slow_ansible_items_run
    age: -1h
  register: when_last_run
- homebrew:
    update_homebrew: yes
    upgrade_all: yes
    upgrade_options: ignore-pinned
  when: when_last_run.files | length == 0
- homebrew_cask:
    upgrade_all: true
  when: when_last_run.files | length == 0
- mas:
    upgrade_all: true
  when: when_last_run.files | length == 0
- file:
    state: touch
    path: /tmp/slow_ansible_items_run
  when: when_last_run.files | length == 0
