- name: Homewbrew Taps
  homebrew_tap:
    name: '{{ homebrew_taps }}'
- name: Ensure homebrew package hash file exists
  copy:
    content: ''
    dest: /tmp/homebrew_package_hash
    force: false
    mode: 'u=rw,g=,o='
- name: Get hash of last homebrew package install list
  slurp:
    src: /tmp/homebrew_package_hash
  register: homebrew_package_hash
- name: Homebrew Packages
  when: homebrew_package_hash['content'] != ( ','.join(homebrew_packages) | hash('sha256') | b64encode )
  block:
    - name: Install Homebrew packages
      homebrew:
        name: '{{ homebrew_packages }}'
    - name: Save hash of homebrew package install list
      copy:
        content: "{{ ','.join(homebrew_packages) | hash('sha256') }}"
        dest: /tmp/homebrew_package_hash
        mode: 'u=rw,g=,o='
- name: Ensure Homebrew Cask hash file exists
  copy:
    content: ''
    dest: /tmp/homebrew_cask_hash
    force: false
    mode: 'u=rw,g=,o='
- name: Get hash of last Homebrew cask install list
  slurp:
    src: /tmp/homebrew_cask_hash
  register: homebrew_cask_hash
- name: Homebrew Casks
  when: homebrew_cask_hash['content'] != ( ','.join(homebrew_casks) | hash('sha256') | b64encode )
  block:
    - name: Install Homebrew Casks
      homebrew_cask:
        accept_external_apps: true
        name: '{{ homebrew_casks }}'
    - name: Save hash of homebrew cask install list
      copy:
        content: "{{ ','.join(homebrew_casks) | hash('sha256') }}"
        dest: /tmp/homebrew_cask_hash
        mode: 'u=rw,g=,o='
- name: Install AppStore Apps
  mas:
    state: present
    id: '{{ app_store_apps }}'
  when: ansible_facts.system == "Darwin"

# Potentially super slow stuff
- name: Check for last run of slow stuff
  find:
    paths: /tmp
    pattern: slow_ansible_items_run
    age: -1h
  register: when_last_run
- name: Slow stuff
  when: when_last_run.files | length == 0
  block:
    - name: Update everything Homebrew
      homebrew:
        update_homebrew: true
        upgrade_all: true
        upgrade_options: ignore-pinned
    - name: Update Homewbrew casks
      homebrew_cask:
        upgrade_all: true
    - name: Update AppStore apps
      mas:
        upgrade_all: true
      when:
        - when_last_run.files | length == 0
        - ansible_facts.system == "Darwin"
    - name: Log run of slow stuff
      file:
        state: touch
        path: /tmp/slow_ansible_items_run
        mode: 'u=rw,g=,o='
