- name: Set up Prezto git repo
  git:
    repo: git@github.com:ThisGuyCodes/prezto.git
    dest: ~/.zprezto
    recursive: true
  environment:
    GIT_TERMINAL_PROMPT: "0"
- name: Enumerate prezto runcoms
  find:
    paths:
      - ~/.zprezto/runcoms
    patterns: '^(?!.*[.]md$).*$'
    use_regex: true
  register: prezto_runcoms
- name: Link prezto runcoms 
  file:
    state: link
    path: "~/.{{ item['path'].split('/')[-1] }}"
    src: "{{ item['path'] }}"
    force: true
  loop: "{{ prezto_runcoms['files'] }}"
  loop_control:
    label: "{{ item['path'].split('/')[-1] }}"
