eval $(rbenv init - zsh)
eval $(thefuck --alias)

export BAT_THEME="Visual Studio Dark+"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
alias -g -- --help='2>&1 | bat --lanaguage=help --style=plain'
alias bathelp='bat --plain --language=help'
help() {
    "$@" --help 2>&1 | bathelp
}
alias batlog='bat --paging=never -l log'
battail() {
    tail -f "$@" | batlog
}
alias cat=bat